replicaCount: 1

image:
  repository: shinnyriver/myreact
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  nodePort: 30000

resources: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: false  # 필요하면 true로 변경
  name: react-app-sa

ingress:
  enabled: false  # true로 설정하면 Ingress 리소스 생성
  annotations: {}
  hosts:
    - host: react.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
